### ISSUE TITLE
Feat:Add Sorting Feature for Media Items Based on Name ,Type,Size etc

### ISSUE THREAD

**Issue by Rajgupta36** [AOSSIE-Org/PictoPy#101]
### Describe the feature

# Feature: Sorting Media Items by Type

## Overview
This feature introduces the ability to sort media items based on their type, determined by their file extensions or media categories. It provides an easy way for users to organize and locate specific types of files .

---

## Sorting Options
The following sorting types are supported:

1. **Sort by Name**:
   - **Descending Order**: Z to A.
   - **Ascending Order**: A to Z.

2. **Sort by Size**:
   - Orders files by their size in ascending order.

3. **Sort by Date**:
   - Orders files by their creation or modification date, with the most recent files appearing first.

4. **Sort by File Type**:
   - Media items are grouped and ordered alphabetically based on their extensions (e.g., `.jpg`, `.png`, `.mp4`).

---

## Key Benefits

- Quickly find and organize files by type in large collections.
- Enhances efficiency by simplifying access to specific file types or attributes.

---

### Customizable and Scalable
- Works seamlessly with existing sorting criteria such as "Date" and "Name."
- Easily extendable for additional media-related attributes in the future.

---

## Future Scope
This feature is designed to be extensible, allowing additional sorting criteria or advanced filtering options to be added as needed.

---

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b5fce4e2-5a71-4811-bef0-761bb3e9609b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Rajgupta36** [comment]
@Pranav0-0Aggarwal Sir, may I work on this issue?

**Comment by Rajgupta36** [comment]
@Pranav0-0Aggarwal sir , I am working on this new feature . could you please assign it to me ?

**Comment by ManishxNinja** [comment]
Any updates?,  I want to work on this issue ,please assign it to me

**Comment by Rajgupta36** [comment]
@ManishxNinja, I implemented this feature locally, but @Pranav0-0Aggarwal sir is inactive, so I didn't create a PR.

**Comment by Pranav0-0Aggarwal** [comment]
@Rajgupta36 assigned it to you

**Comment by k-vijay-05** [comment]
@Pranav0-0Aggarwal  is still the issue open . can i work on this?
