### ISSUE TITLE
Feat: Change twitter logo -from bird to X

### ISSUE THREAD

**Issue by Gorachand-Senapati** [AOSSIE-Org/PictoPy#102]
### Describe the feature

The issue involves changing the Twitter icon from its iconic bird symbol to the letter "X," reflecting the platform's rebranding under new ownership. This shift signifies a move towards a new identity and vision for the social media platform.

### Add ScreenShots

![Screenshot 2024-12-12 015654](https://github.com/user-attachments/assets/3cb119f9-bd87-455f-b156-c4372d4904fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sushant041** [comment]
Hi @Gorachand-Senapati, could you please assign this issue to me? Thanks!

**Comment by Gorachand-Senapati** [comment]
@Sushant041 I already work on the issue.

**Comment by ManishxNinja** [comment]
is the issue is resolved or it is still open any updates?
