### ISSUE TITLE
BUG: Added Images folder

### ISSUE THREAD

**Issue by Jibesh10101011** [AOSSIE-Org/PictoPy#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/8c41db91-a06b-40d3-b04f-c121a675c70a)

**Images folder is removed it will give error  during adding a folder if images folder is deleted** 

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by suryaanshah** [comment]
Hi @Jibesh10101011 !
Could you please provide the details of the error, as well as instructions to reproduce it?

I'd be happy to debug this once these are cleared up.

**Comment by Jibesh10101011** [comment]
@suryaanshah if you run the application in your device during adding images from a folder 

What will happen in backend , here it will find 'images' folder for storing the images from the **folder you have uploaded from frontend** but as there is no **images** folder in the directory from backend it will throw error
