### ISSUE TITLE
BUG: Proper reporting of duplicate album error.

### ISSUE THREAD

**Issue by rahulharpal1603** [AOSSIE-Org/PictoPy#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Whenever we try to create an album which already exists, the server gives a 500 Error code. The frontend doesn't display any error for this.  Also, the edit album description functionality is not functional. 

Solution: Updating the /albums/create-album API Endpoint to throw meaningful errors with correct code to the frontend, displaying this error appropriately and alerting the user. Also, we need to fix the bugs in the edit album description functionality

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by rahulharpal1603** [comment]
@Pranav0-0Aggarwal I can work on this. Please assign me. This task will be completed within few hours.

**Comment by Pranav0-0Aggarwal** [comment]
sure, Rahul
assigned it to you
