### ISSUE TITLE
Feat: UI/UX Revamp

### ISSUE THREAD

**Issue by rahulharpal1603** [AOSSIE-Org/PictoPy#113]
# UI/UX Revamp for PictoPy - Comprehensive Interface Enhancement

## Overview
This issue outlines a comprehensive UI/UX revamp plan for PictoPy, focusing on improving visual consistency, responsiveness, and user experience across all major components of the application. I will raise one [PR ](https://github.com/AOSSIE-Org/PictoPy/pull/114) for this whole thing and make commits to that PR until all the subtasks are done. 

### 1. Sidebar Modernization
- [x] Replace current icons with Lucide React icons
- [x] Implement new hover effects
  - Add smooth transitions
  - Include visual feedback
- [x] Update overall sidebar styling
  - Modern color scheme
  - Consistent spacing
  - Better visual hierarchy

**Before** (this doesn't have hover effect, icons could be better and there is unwanted extra space at the botton): 

![WhatsApp Image 2024-12-18 at 23 58 16_54eabfde](https://github.com/user-attachments/assets/4af4314e-2495-4b0a-a35f-83fb77868e6a)

**After** (has smooth hover effects and lucide icons look modern and relevant):

https://github.com/user-attachments/assets/a9124434-f5ef-4aaf-bd5a-d3e41ab8acbf

### 2. Tauri Configuration Update
- [x] Update app name in Tauri configuration file
- [x] Replace default icons with custom [PictoPy](https://aossie-org.github.io/PictoPy/assets/PictoPy-logo.png) icons

### 3. Home Page and AI Tagging Page Enhancement
- [x] Update the grid layout, currently the media queries defined for number of columns doesn't yield good fits for all screen sizes. 
- [x] Close the image viewer when clicked in any blank area (highlighted with orange):
![image](https://github.com/user-attachments/assets/f2f6cda9-2779-4056-9144-8bdfd63136a5)

### 4. Videos Page Optimization
- [x] Implement conditional rendering for navigation buttons
  - Hide previous button when on first video
  - Hide next button when on last video
  - Hide both buttons when there are no videos
- [x] Enhance grid layout

### 5. Albums Page Fixes
- [x] Implement proper cover image handling for empty albums
  - Add fallback image support
  - Fix image path issues
- [x] Fix remove icon deformation issue
  - Redesign the red cross icon
  - Ensure consistent icon sizing
- [x] Implement real-time album list updates
  - Fix back button navigation issue (Problem: The album cover images do no referesh automatically after clicking back)
- [x] Enhance overall responsiveness

### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by rahulharpal1603** [comment]
@Pranav0-0Aggarwal Please assign this to me, I have raised the PR and I have completed the subtask 1.  Further tasks will be commited within 1-2 days

**Comment by Pranav0-0Aggarwal** [comment]
done

**Comment by rahulharpal1603** [comment]
This Issue will take some time, probably one day more because many new minor issues are revealed.
