### ISSUE TITLE
Feat: Add "Select All" Option for Deleting Photos in AI Tagging

### ISSUE THREAD

**Issue by zenitsu0509** [AOSSIE-Org/PictoPy#118]
### Describe the feature

Description:
Currently, users must select photos one by one to delete them in the AI tagging interface. This process is time-consuming, especially when dealing with a large number of photos. A "Select All" option should be added to allow users to select all photos at once and delete them in bulk. This feature will improve user efficiency and experience.

### Add ScreenShots

Proposed Solution:

Add a "Select All" checkbox in the photo selection UI.
Modify the delete functionality to handle bulk deletion of selected photos.
Update the backend API to accept and process multiple photo IDs for deletion in a single request.
![Screenshot 2024-12-20 163208](https://github.com/user-attachments/assets/80083068-e425-43c5-ae4e-71030a168e3e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Jibesh10101011** [comment]
@zenitsu0509 for your reference 

https://github.com/user-attachments/assets/74cecb4b-77f7-4ceb-9654-eac37a6b92b6

In the current deletion features you are deleting multiple images by selecting them but you can add a new feature **select all** button where by clicking that button you can select all images and also add a loading with it

**Comment by Rajgupta36** [comment]
@zenitsu0509, if you are not working on this issue, can I take it?

**Comment by zenitsu0509** [comment]
sure 😊

**Comment by Rajgupta36** [comment]
thanks . hii @Pranav0-0Aggarwal sir pls assign this issue to me

**Comment by namanjain24-sudo** [comment]
@Pranav0-0Aggarwal,Sir pls assign this issue to me...

**Comment by Rishab87** [comment]
@Pranav0-0Aggarwal I have fixed this issue, please check

**Comment by Rajgupta36** [comment]
@Rishab87 , please do not jump straight into solving the issue without approving the assignment request. i am waiting for @Pranav0-0Aggarwal approval.

**Comment by Pranav0-0Aggarwal** [comment]
@Rajgupta36 Rishabh made a PR regarding this issue, apologies for missing your messages
@Rishab87 next time, plz don't jump on working without getting the issue assigned, this might lead to waste of resources leading to duplicate work going on for same issue.

**Comment by Rishab87** [comment]
I'm really sorry @Pranav0-0Aggarwal, @Rajgupta36  , next time I'll keep this in mind, it was a one line change and it was pending from past 5 days so I just went ahead making changes, I'll definetly get myself issue assigned from next time

**Comment by zenitsu0509** [comment]
Thanks to all for adding this feature😊
