### ISSUE TITLE
BUG: RAM and CPU overload for higher quality images

### ISSUE THREAD

**Issue by rahulharpal1603** [AOSSIE-Org/PictoPy#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## What happened?

When we add a folder with very lightweight images (e.g. the tests folder in our repository), the gallery works fine and doesn't consume much resources: 

![WhatsApp Image 2024-12-23 at 16 22 23_dd5abda2](https://github.com/user-attachments/assets/bfe9a5d1-4cd1-479d-896a-4bac23d7124d)

But when I added a folder of only 330 MB, containing 73 images, the gallery took up almost 3.5 GB of RAM and 20-30% of continuous CPU usage on my laptop (Core i7 11th Gen with 16 GB RAM).  Also, if you view this video I captured using my phone(to avoid the influence of the screen recorder on performance), you will notice the performance issues when switching to the next page and scrolling. 

video(unlisted on YouTube): https://www.youtube.com/watch?v=gfWAamOvsdk

![WhatsApp Image 2024-12-23 at 16 34 29_3cc4956a](https://github.com/user-attachments/assets/f96be192-7efd-4bfe-936b-3fbed8c1cb9f)

## Proposed solution: 

1) To generate a folder named PictoPy.thumbnails inside the selected folder. 
2) This folder will contain resized images from its parent folder
3) This folder will not take up a lot of space. Only around 100 -300 kB per image. 
4) While displaying the gallery, we display images from this thumbnails folder, and when the user clicks the image to view it, we only bring up the original image. This will considerably improve the app's performance and limit the RAM usage to under 500 MB. 
5) To generate thumbnails, we need to use the well-known image processing library for Rust, which is [this](https://crates.io/crates/image). 
6) After generating the thumbnails, we also need to send paths for the thumbnails; for this, we need to modify the [get_images_with_cache()](https://github.com/AOSSIE-Org/PictoPy/blob/main/frontend/src-tauri/src/services/mod.rs#L34) function.

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by rahulharpal1603** [comment]
@Pranav0-0Aggarwal I am working on this issue, please assign this to me.

**Comment by Jibesh10101011** [comment]
@rahulharpal1603 I have tested in my device too , where folder size 325 MB 

https://github.com/user-attachments/assets/93d4afd7-e0d4-4933-a50f-26a96fb353eb


You can see clearly that this Pictopy application is using very amount of RAM which is less than 100 MB 

My Device Configuration : ((Core i5 11th Gen with 8 GB RAM) It's totally works fine for large folder size and it should be because 
here image is processing one by one not a bulk amount of images at a time 

So , I think it's the problem with your WebView not with Pictopy

**Comment by rahulharpal1603** [comment]
> @rahulharpal1603 I have tested in my device too , where folder size 325 MB
> 
>  Pictopy_O1mYrkgAha.mp4 
> You can see clearly that this Pictopy application is using very amount of RAM which is less than 100 MB
> 
> My Device Configuration : ((Core i5 11th Gen with 8 GB RAM) It's totally works fine for large folder size and it should be because here image is processing one by one not a bulk amount of images at a time
> 
> So , I think it's the problem with your WebView not with Pictopy

I think you are not able to reproduce the results because your folder contains a lot of small sized photos considering that there are 9000+ images in a 345MB folder. Also, can you sort the task manager list in descending order of RAM usage and try again with this set of images? : https://drive.google.com/file/d/1e3WDIjJS4KJiVNYipXTxXC9x0iq2BPY_/view

This folder has only 73 images and size is around 300 MB

Also, try to scroll through the home page as well as the AI tagging page, when you will scroll or switch to next page, the CPU and RAM will be overloaded

This is issue occurs when you load the above folder for the Home page, and for AI tagging page also, this would bear the same results.

**Comment by rahulharpal1603** [comment]
> I thin
> 
> > @rahulharpal1603 I have tested in my device too , where folder size 325 MB
> > Pictopy_O1mYrkgAha.mp4
> > You can see clearly that this Pictopy application is using very amount of RAM which is less than 100 MB
> > My Device Configuration : ((Core i5 11th Gen with 8 GB RAM) It's totally works fine for large folder size and it should be because here image is processing one by one not a bulk amount of images at a time
> > So , I think it's the problem with your WebView not with Pictopy
> 
> I think you are not able to reproduce the results because your folder contains a lot of small sized photos considering that there are 9000+ images in a 345MB folder. Also, can you sort the task manager list in descending order and try again with this set of images? : https://drive.google.com/file/d/1e3WDIjJS4KJiVNYipXTxXC9x0iq2BPY_/view
> 
> This folder has only 73 images and size is around 300 MB

Also, try to scroll through the home page as well as the AI taggin page, when you will scroll or switch to next page, the CPU and RAM will be overloaded

**Comment by Jibesh10101011** [comment]
I have tested with this https://drive.google.com/file/d/1e3WDIjJS4KJiVNYipXTxXC9x0iq2BPY_/view too

watch here : 

https://s3.eu-north-1.amazonaws.com/jibeshroy.static.dev/Pictopy/Pictopy_dWWlsCc8Uo.mp4


It's not consuming 3GB for a little moment it peaks at 1.2 GB after it was always < 1 GB

**Comment by rahulharpal1603** [comment]
> I have tested with this https://drive.google.com/file/d/1e3WDIjJS4KJiVNYipXTxXC9x0iq2BPY_/view too
> 
> watch here :
> 
> https://s3.eu-north-1.amazonaws.com/jibeshroy.static.dev/Pictopy/Pictopy_dWWlsCc8Uo.mp4
> 
> It's not consuming 3GB for a little moment it peaks at 1.2 GB after it was always < 1 GB

Yes, as you can see the webview task on the task manager suddenly consumes 1.2 GB while displaying just 9 images. Also, as you can notice, when you switch pages to load only 6 images, the app struggles, and we have jitters. This makes up for a bad user experience. 


 My home page had 20 images because in this PR https://github.com/AOSSIE-Org/PictoPy/pull/114, I have changed the number of images to 20 per page because on a bigger screen if you display just 9 photos per page, it would look very odd for an image gallery. That is why my app was peaking at around 3 GB of RAM just to display 20 photos.

**Comment by rahulharpal1603** [comment]
So, if we just display thumbnails, we would not exceed even 500 MB of usage, even when there are 20 images per page.

**Comment by Jibesh10101011** [comment]
> > I have tested with this https://drive.google.com/file/d/1e3WDIjJS4KJiVNYipXTxXC9x0iq2BPY_/view too
> > watch here :
> > https://s3.eu-north-1.amazonaws.com/jibeshroy.static.dev/Pictopy/Pictopy_dWWlsCc8Uo.mp4
> > It's not consuming 3GB for a little moment it peaks at 1.2 GB after it was always < 1 GB
> 
> Yes, as you can see the webview task on the task manager suddenly consumes 1.2 GB while displaying just 9 images. Also, as you can notice, when you switch pages to load only 6 images, the app struggles, and we have jitters. This makes up for a bad user experience.
> 
> My home page had 20 images because in this PR #114, I have changed the number of images to 20 per page because on a bigger screen if you display just 9 photos per page, it would look very odd for an image gallery. That is why my app was peaking at around 3 GB of RAM just to display 20 photos.

So, @rahulharpal1603, I want to clarify one thing: you are saying that when the number of images per page increases for higher-quality images (default was 9), and in this case, the number of images per page is 20, it occupies a large portion of the CPU, which leads to a poor user experience , Am I right?

**Comment by rahulharpal1603** [comment]
> > > I have tested with this https://drive.google.com/file/d/1e3WDIjJS4KJiVNYipXTxXC9x0iq2BPY_/view too
> > > watch here :
> > > https://s3.eu-north-1.amazonaws.com/jibeshroy.static.dev/Pictopy/Pictopy_dWWlsCc8Uo.mp4
> > > It's not consuming 3GB for a little moment it peaks at 1.2 GB after it was always < 1 GB
> > 
> > 
> > Yes, as you can see the webview task on the task manager suddenly consumes 1.2 GB while displaying just 9 images. Also, as you can notice, when you switch pages to load only 6 images, the app struggles, and we have jitters. This makes up for a bad user experience.
> > My home page had 20 images because in this PR #114, I have changed the number of images to 20 per page because on a bigger screen if you display just 9 photos per page, it would look very odd for an image gallery. That is why my app was peaking at around 3 GB of RAM just to display 20 photos.
> 
> So, @rahulharpal1603, I want to clarify one thing: you are saying that when the number of images per page increases for higher-quality images (default was 9), and in this case, the number of images per page is 20, it occupies a significant portion of the CPU, which leads to a poor user experience , Am I right?

Yes, exactly.

**Comment by rahulharpal1603** [comment]
Also, I have observed that  Google Drive uses the same approach to display photos; when we open a folder with images, we will notice that the photos are not very high quality, but when we double-click to open them, they render in full resolution.

**Comment by Jibesh10101011** [comment]
> Also, I have observed that  Google Drive uses the same approach to display photos; when we open a folder with images, we will notice that the photos are not very high quality, but when we double-click to open them, they render in full resolution. 

Yes @rahulharpal1603

**Comment by Pranav0-0Aggarwal** [comment]
Great discussion and great idea.
assigned it to you Rahul
