### ISSUE TITLE
Feat: Enhance Docker Compose Configuration with Additional Functionality & Bug: Cann't Add folder 

### ISSUE THREAD

**Issue by Jibesh10101011** [AOSSIE-Org/PictoPy#121]
## Feature : docker-compose.yml

Currently, running the Pictopy frontend and backend images requires separate, lengthy commands to execute them individually. To simplify this process,  propose adding a **docker-compose.yml** file to the project. This configuration would allow us to manage both the frontend and backend images together using simple Docker Compose commands such as 

> For building the  Docker image 
```bash
docker compose build
````
> For running all the services 
```bash
docker compose up
````
> clean up the environment when you no longer need the services running.
```bash
docker compose down
```
-  ### And will also add a documentation for docker-compose.yml

## Bug : Failed to add folder ( if run via Docker )

![bug-docker](https://github.com/user-attachments/assets/8f2c1e6c-a5a1-45ae-a6b3-f679720ffbe7)

## Warning : dconf-WARNING

![warning-docker](https://github.com/user-attachments/assets/93506d33-cf46-41ae-8c83-3a425b93c1fa)

### Feature : Docker-Compose 

https://github.com/user-attachments/assets/e1e35349-12d7-492c-af33-43adfb6860f9

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Jibesh10101011** [comment]
@Pranav0-0Aggarwal I am working in this Issue , Can you assign it to me ?

**Comment by Pranav0-0Aggarwal** [comment]
done
