### ISSUE TITLE
Feat:To add a light/dark mode feature in the main gallery 

### ISSUE THREAD

**Issue by priyanshu9899** [AOSSIE-Org/PictoPy#129]
### Describe the feature

The idea is to add light /dark mode button in the main gallery page so that user can easily toggle as per their choice .

### Add ScreenShots

![Uploading Screenshot 2024-12-24 at 10.50.45 PM.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyanshu9899** [comment]
hey @Pranav0-0Aggarwal I am currently working on this issue please assign it to me .

**Comment by Pranav0-0Aggarwal** [comment]
done

**Comment by priyanshu9899** [comment]
i have pulled a PR , you can review that
