### ISSUE TITLE
BUG: HTML tag error in Nav component .

### ISSUE THREAD

**Issue by Abhiifour** [AOSSIE-Org/PictoPy#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/91b3b0e7-672b-48c7-a09a-7af1b2a7edbf)

Opening div tag is missing in NavBar component . 

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by Pranav0-0Aggarwal** [comment]
Assigned this to you

**Comment by KKSurendran06** [comment]
Hi @Abhiifour 
This issue was resolved in PR #123
