### ISSUE TITLE
BUG: The loading... ui fix .

### ISSUE THREAD

**Issue by Abhiifour** [AOSSIE-Org/PictoPy#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/12108d95-42db-4f3f-8d08-b0845a3360ef)
The Loading... component when you intially hit the home page looks very basic . needs minor ui improvement .

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by Pranav0-0Aggarwal** [comment]
assigned it to you

**Comment by abhiifour** [comment]
hey @Pranav0-0Aggarwal  
fixed it in PR #139
