### ISSUE TITLE
Feat: Implementation of react tanstack query

### ISSUE THREAD

**Issue by Rishab87** [AOSSIE-Org/PictoPy#137]
### Describe the feature

Instead of manually handling data from backend we can implement a custom implementation of tanstack query, which will make the code more scalable. In future if we want to add more api calls and want more complex data handling, it will be very easy to manage with this. It will reduce code duplication and prop drilling by a lot. But if the functionality of the app is limited to what it is now then I think just context api or this code will be sufficient

### Add ScreenShots

no screenshots to attatch

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Pranav0-0Aggarwal** [comment]
Assigned.

**Comment by Rishab87** [comment]
@Pranav0-0Aggarwal I've implemented it please check
