### ISSUE TITLE
BUG: Sidebar Responsiveness for Split Screen Scenarios

### ISSUE THREAD

**Issue by asmit27rai** [AOSSIE-Org/PictoPy#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# Enhance Sidebar Responsiveness for Split Screen Scenarios

### Description
The sidebar in **PictoPy** currently lacks full responsiveness when the application is used in split-screen mode or on varying desktop screen sizes. This results in layout inconsistencies and usability challenges for users who rely on split-screen workflows.

---

### Expected Behavior
- The sidebar should dynamically adjust its width and layout to fit the available screen space.  
- All functionalities (e.g., navigation, search, settings) should remain fully accessible and visually appealing, regardless of the window size.  

---

### Steps to Reproduce
1. Open the **PictoPy** application on a desktop.  
2. Resize the application window or use it in split-screen mode alongside another app.  
3. Observe how the sidebar responds to the changes in window size.  

---

https://github.com/user-attachments/assets/ce057b6c-0d67-47da-b9fa-531ffaf8f057

### Record

- [x] I agree to follow this project's Code of Conduct

**Comment by asmit27rai** [comment]
@Pranav0-0Aggarwal Pls Assign This issue to me.

**Comment by Pranav0-0Aggarwal** [comment]
Done
