### ISSUE TITLE
Lack of Clarity in README and Absence of Comments in main.py

### ISSUE THREAD

**Issue by animeshchaudhri** [AOSSIE-Org/PictoPy#15]
The project's documentation and codebase suffer from inadequate clarity and lack of explanatory comments, respectively. This can potentially hinder understanding, maintenance, and collaboration among developers.

- The README lacks sufficient information regarding project setup, usage, and dependencies. Users and contributors might struggle to understand how to get started with the project 
- Multiple README files are present within the project repository, leading to redundancy.
- The main.py file lacks meaningful comments, making it hard to understand the logic and functionality of the code.

![image](https://github.com/AOSSIE-Org/PictoPy/assets/111721851/d4f57989-8afc-4193-9165-0aee48a7f645)

**Comment by animeshchaudhri** [comment]
Please assign me this issue. I would like to work on this

**Comment by Pranav0-0Aggarwal** [comment]
Done
