### ISSUE TITLE
BUG:PictoPy title and welcome user overlaps in small screen

### ISSUE THREAD

**Issue by red-panda3** [AOSSIE-Org/PictoPy#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-12-28 114128](https://github.com/user-attachments/assets/88b51f9a-66bb-43f2-81cd-bf4e0516a139)

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by red-panda3** [comment]
sir,please assign this  issue  to me

**Comment by arorabhavik1001** [comment]
hi, i can resolve this issue. kindly assign it to me.

**Comment by arorabhavik1001** [comment]
Hi, i've fixed this issue and raised the [PR](https://github.com/AOSSIE-Org/PictoPy/pull/158)

**Comment by red-panda3** [comment]
Sir,issue is fixed  #167
