### ISSUE TITLE
BUG: DELETE method uses JSON body – Not RESTful

### ISSUE THREAD

**Issue by Yash114Bansal** [AOSSIE-Org/PictoPy#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Albums API's DELETE method is designed to accept data through a JSON request body. While this approach technically works, it deviates from RESTful principles and standard practices.

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by Pranav0-0Aggarwal** [comment]
Elaborate and raise a detailed issue.
