### ISSUE TITLE
[Feature] : Keyboard navigation using the left and right arrow keys

### ISSUE THREAD

**Issue by raggettii** [AOSSIE-Org/PictoPy#45]
**Expected Behavior:**
The app should display the previous video/image when the left arrow key is pressed.
When the right arrow key is pressed, the app should display the next video/image.

**Current Behavior:**
Right now we need to click on the arrow button to navigate through the video/image.

**Comment by ChandraDevs1** [comment]
can i work on it

**Comment by raggettii** [comment]
there's already PR raised.

**Comment by rakhiiprajapati** [comment]
Hello PR 
Dear PR, please assign me this issue i am changeing to the header and main content also look 
i make a better and more beautiful website   i am request you please assign me this issue

**Comment by geeky33** [comment]
.take

**Comment by Pranav0-0Aggarwal** [comment]
Anyone working on this issue?

**Comment by kartik-212004** [comment]
I want to work on this issue

**Comment by Pranav0-0Aggarwal** [comment]
sure, @kartik-212004 assigned this to you

**Comment by raggettii** [comment]
@Pranav0-0Aggarwal I already have a pr raised to this issue. Can you please review it once.

**Comment by devanmolx** [comment]
@Pranav0-0Aggarwal Can I work on this issue?

**Comment by ManishxNinja** [comment]
> sure, @kartik-212004 assigned this to you

I had raised the PR which solved the issue and their is no merge conflicts
