### ISSUE TITLE
Add Issue Templates to the Repository

### ISSUE THREAD

**Issue by jitendra-ky** [AOSSIE-Org/PictoPy#56]
**Description:**  
The repository currently lacks issue templates. Adding these templates (e.g., bug report, feature request, etc.) will streamline the process of submitting issues and improve organization.  

**Proposed Solution:**  
- Create a `.github/ISSUE_TEMPLATE` directory.  
- Add markdown files for standard templates (e.g., bug_report.md, feature_request.md).  
- Ensure templates include fields for detailed reproduction steps, expected behavior, etc.  

**Additional Context:**  
Having templates will encourage structured and clear communication.

**Comment by jitendra-ky** [comment]
if find this enhancement useful then you can assign it to me, thank you

**Comment by Pranav0-0Aggarwal** [comment]
assigning this to you
