### ISSUE TITLE
Tauri fails to run on WSL or linux.

### ISSUE THREAD

**Issue by Rajgupta36** [AOSSIE-Org/PictoPy#58]
**Summary**
When running a Tauri application in WSL (Windows Subsystem for Linux) with Ubuntu, the build process fails . This issue makes it challenging to use Tauri in a WSL-based development environment.

**Steps to Reproduce**

1 Go to frontend folder.
2. Install the required dependencies for Tauri, including Rust and Node.js.
3. Attempt to run the application using npm run tauri dev command.

**Environment Details**

- Operating System: Ubuntu 22.04.4 LTS on WSL 2
- Node.js Version: 22.2.0
- Rust Version: 1.82.0
- WSL Version: WSL 2

**Logs and Error Messages**

![Screenshot 2024-11-16 194329](https://github.com/user-attachments/assets/7aec9b4e-3de9-4bc8-980f-2a014a4a2233)

![Screenshot 2024-11-16 194237](https://github.com/user-attachments/assets/1c8a764c-cb1d-4457-8447-48bac0ff3ff3)

![Screenshot 2024-11-16 194246](https://github.com/user-attachments/assets/fdcfdffb-598a-481e-933d-0bb08f22bbd5)

![Screenshot 2024-11-16 194254](https://github.com/user-attachments/assets/760fecfc-370d-4e9c-bad8-6b2e1089f39a)

**Additional Context**

Running the same Tauri application on native Windows works correctly, suggesting the issue is specific to the WSL environment.

**Comment by Pranav0-0Aggarwal** [comment]
@Dushyantbha012 isn't this fixed in your PR?

**Comment by Dushyantbha012** [comment]
@Pranav0-0Aggarwal the issue I fixed was the signing of private and public keys during the build process, this issue is regarding the dependencies which one should have in their OS to run tauri and rust

**Comment by Pranav0-0Aggarwal** [comment]
got it, so this is an open issue for now.

**Comment by Dushyantbha012** [comment]
I think it is solved by the PR #60 as this installs all the required dependencies

**Comment by Rajgupta36** [comment]
> I think it is solved by the PR #60 as this installs all the required dependencies

I use this project on WSL and Linux. After PR #60, it works well on Linux, but on WSL, it throws some permission errors.so what i can do create a new issue or follow up on this issue. @Pranav0-0Aggarwal

**Comment by Dushyantbha012** [comment]
Can you elaborate what's the issue exactly? @Rajgupta36

**Comment by Rajgupta36** [comment]
![image](https://github.com/user-attachments/assets/87a0be1f-a7b7-40b1-831a-ee6333a1276c)
whenever i run build command on wsl,it fails @Dushyantbha012

**Comment by Dushyantbha012** [comment]
I have solved this issue in pr #68
