### ISSUE TITLE
Creating a test to validate the feature of captioning images retrieved from the database

### ISSUE THREAD

**Issue by kamisama-coder** [AOSSIE-Org/PictoPy#61]
made using the transformers class BlipForConditionalGeneration  and the model name is salesforce/blip-image-captioning-base.
the future scope involves :
1.Enhanced Caption Clustering in a Database
Use unsupervised clustering algorithms, like DBSCAN or k-means, to organize images in the database based on their captions.
Enable dynamic clustering updates when new images are added to the database.
2. Query-Based Image Search
Implement semantic search to allow users to find images using natural language queries.
For example, a query like "A dog playing in a garden" should retrieve images with similar content.

**Comment by Pranav0-0Aggarwal** [comment]
great idea! Will add this in the project milestones for the upcoming year.

**Comment by kamisama-coder** [comment]
@Pranav0-0Aggarwal can you assign this issue to me

**Comment by Pranav0-0Aggarwal** [comment]
assigned

**Comment by kamisama-coder** [comment]
@Pranav0-0Aggarwal can you review the PR

**Comment by kamisama-coder** [comment]
@Pranav0-0Aggarwal validate the PR

**Comment by kamisama-coder** [comment]
@Pranav0-0Aggarwal please review the PR

**Comment by kamisama-coder** [comment]
@Pranav0-0Aggarwal tell me changes to be made in PR.

**Comment by bassamadnan** [comment]
@kamisama-coder isn't 1 already done? the DBSCAN has already been implemented, and reclustering happens after 5 new images are added i believe.

**Comment by kamisama-coder** [comment]
@bassamadnan I understand, brother. However, I thought that face embeddings were being used to create clusters. I was considering the idea of forming clusters by combining face embeddings and caption embeddings.

**Comment by kamisama-coder** [comment]
opening the new issue
