### ISSUE TITLE
Optimize Dockerfile to Leverage Layer Caching and Improve Build Times (Backend)

### ISSUE THREAD

**Issue by anmol2710** [AOSSIE-Org/PictoPy#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current Dockerfile in the project rebuilds from scratch every time there are changes in the source code, even when the dependencies or system-level packages haven't changed. This results in inefficient caching and unnecessarily long build times.

The main issues is the entire source code is copied early in the Dockerfile, which causes Docker to invalidate subsequent cached layers (e.g., dependency installation) whenever the code changes.

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by devanmolx** [comment]
@Pranav0-0Aggarwal , can i work on this issue ?

**Comment by Pranav0-0Aggarwal** [comment]
sure

**Comment by Pranav0-0Aggarwal** [comment]
@anmol2710 this is a duplicate issue, check #63

**Comment by devanmolx** [comment]
@Pranav0-0Aggarwal Issue #63 is for frontend Dockerfile and this issue is for backend Dockerfile

**Comment by Pranav0-0Aggarwal** [comment]
i am assigning you to the issue #63 please coordinate, with Raj, multiple issues for similar work feels useless.
