### ISSUE TITLE
BUG:Security vulnerability , .env file committed to repo

### ISSUE THREAD

**Issue by yashpandey06** [AOSSIE-Org/PictoPy#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

.env file is being pushed to the repo, we should rather use some other means to keep these secrets private right ?

<img width="880" alt="Screenshot 2024-11-20 at 4 12 52 PM" src="https://github.com/user-attachments/assets/53e16fd3-7692-4884-9759-1607c54e36bf">

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by yashpandey06** [comment]
@Pranav0-0Aggarwal can you please help explain the need of this .env file ?

**Comment by Dhruv-pahuja** [comment]
i am working on it

**Comment by yashpandey06** [comment]
@Dhruv-pahuja please from next time let's first enquire if the person who has raised the issue is working on it or not ...that's how open source works if. I am not wrong !.

**Comment by yashpandey06** [comment]
Let's not jump right into solving issue without consulting the issue master 😔.

**Comment by Dhruv-pahuja** [comment]
ohh so sorry @yashpandey06 , i will consider this from next time and i may close this PR if you are working on it.

**Comment by yashpandey06** [comment]
@Dhruv-pahuja please don't close the PR ...but lets be active from next time .

**Comment by Rajgupta36** [comment]
@yashpandey06 , I think env file only contains default keys that are available to everyone. Also, in the Docker setup, he uses these keys as env variables.

**Comment by yashpandey06** [comment]
>  @yashpandey06 , I think env file only contains default keys that are available to everyone. Also, in the Docker setup, he uses these keys as env variables. 
@Rajgupta36 even then it would be good practise to clarify that this env is the example env somewhat like ".env.example"

**Comment by Rajgupta36** [comment]
@yashpandey06  yepp, it's good practice .Although I also figured out a few bugs, they are only one or two errors. Should I create a PR for that or include it in a bigger PR?

**Comment by Pranav0-0Aggarwal** [comment]
Hey, Ig @Dushyantbha012 hardcoded the keys, so that's where the .env file came from

is someone working on this issue?

**Comment by Dushyantbha012** [comment]
No I didn't hard-code anything in .env it's @zenitsu0509

**Comment by zenitsu0509** [comment]
can you tell me where it is located @Dushyantbha012

**Comment by zenitsu0509** [comment]
its not a big issue it just contains public and private keys

**Comment by yashpandey06** [comment]
> its not a big issue it just contains public and private keys
> Yeah , it's not , but how about we follow industry  standards 😄 .

**Comment by Dhruv-pahuja** [comment]
I have a suggestion just put the .env file in gitignore and add .env.example to this repo adding these values in that example file

**Comment by yashpandey06** [comment]
> I have a suggestion just put the .env file in gitignore and add .env.example to this repo adding these values in that example file 

Yeah exactly
