### ISSUE TITLE
BUG: Clicking 'Add Image' Button During Album Creation Redirects to a Blank White Page

### ISSUE THREAD

**Issue by Jibesh10101011** [AOSSIE-Org/PictoPy#77]
https://github.com/user-attachments/assets/176ab2f3-43a2-4a1d-a4f9-5e7f588a8493

**When attempting to create a new album in Pictopy, clicking the "Add Image" button redirects to a blank white page. No data or UI elements are displayed, making it impossible to proceed further with the album creation process.**

**Comment by Jibesh10101011** [comment]
@Pranav0-0Aggarwal I am working on this issue . can you assign this to me ?

**Comment by Pranav0-0Aggarwal** [comment]
Assigned
