### ISSUE TITLE
DOC: Add documentation for running Docker file.

### ISSUE THREAD

**Issue by Pranav0-0Aggarwal** [AOSSIE-Org/PictoPy#78]
### What's wrong with the existing documentation

Steps for Setting Up and Running the Dockerized Version of PictoPy

- [ ] Prerequisites
- [ ] List the required tools and system requirements.
- [ ] Clone the PictoPy repository.
- [ ] Build the Docker image using the provided Dockerfile.
- [ ] Run the Docker container.
- [ ] Document probable issues and solutions.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Rajgupta36** [comment]
@Pranav0-0Aggarwal , can i work on it ?

**Comment by Pranav0-0Aggarwal** [comment]
sure, but will you be able to work on so many issues all together?

**Comment by Jibesh10101011** [comment]
@Pranav0-0Aggarwal , I also want to work on this , can I ?

**Comment by Pranav0-0Aggarwal** [comment]
Assigning this to you @Jibesh10101011 
I think @Rajgupta36 already has a lot, if he still wants to work, then you both coordinate.

**Comment by Rajgupta36** [comment]
> Assigning this to you @Jibesh10101011 I think @Rajgupta36 already has a lot, if he still wants to work, then you both coordinate.

@Pranav0-0Aggarwal , sir I have resolved all the issues I was working on.  @Jibesh10101011 i will always be ready to coordinate with you.

**Comment by Pranav0-0Aggarwal** [comment]
sure @Rajgupta36 , assigned this to you too
Please coordinate and work on this issue.

**Comment by Jibesh10101011** [comment]
@Pranav0-0Aggarwal , @Rajgupta36 

Steps for Setting Up and Running the Dockerized Version of PictoPy: A Short Demo

###  Prerequisites : 
Docker Installation

### List the required tools and system requirements.

**Tools** 
Docker: To containerize the application.

**System Requirements**

1. **Operating System** : Any OS that supports Docker (Windows, macOS, Linux).
2. **Hardware** : At least 4 GB of RAM recommended for smooth performance.
3. **Disk Space** : Adequate disk space to store Docker images and containers.

### Clone the PictoPy Repository

git clone https://github.com/AOSSIE-Org/PictoPy.git

### Build the Docker Image Using the Provided Dockerfile

**Backend :**  docker build -t <backend-image_name> .
**Frontend :**  docker build --build-arg TAURI_SIGNING_PRIVATE_KEY=dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5NlF2SjE3cWNXOVlQQ0JBTlNITEpOUVoyQ3ZuNTdOSkwyNE1NN2RmVWQ1a0FBQkFBQUFBQUFBQUFBQUlBQUFBQU9XOGpTSFNRd0Q4SjNSbm5Oc1E0OThIUGx6SS9lWXI3ZjJxN3BESEh1QTRiQXlkR2E5aG1oK1g0Tk5kcmFzc0IvZFZScEpubnptRkxlbDlUR2R1d1Y5OGRSYUVmUGoxNTFBcHpQZ1dSS2lHWklZVHNkV1Byd1VQSnZCdTZFWlVGOUFNVENBRlgweUU9Cg== --build-arg TAURI_SIGNING_PRIVATE_KEY_PASSWORD=pass -t <frontend-image_name> .

### Run the Docker container.

**Backend:** docker run --rm  -p 8000:8000 -it <backend-image_name> 
**Frontend :**  docker run  --rm -p 1420:1420 -it <frontend-image_name> 

### Document Probable Issues and Solutions 

1. Docker Not Installed
**Solution**: Follow the official Docker installation guide for your operating system.

3. Check Line Endings in run.sh:
Ensure that run.sh uses Unix line endings (LF)
**Solution** : You can convert line endings using tools like : **dos2unix run.sh**

4. Port Conflicts
**Solution**: Ensure the ports (1420 for frontend and 8000 for backend) are not being used by other applications. You can change the ports if necessary.

5. Build Errors 
**Solution**: Check the build logs for detailed error messages. Ensure all dependencies are installed and paths are correct.

6. Issue: Missing Environment Variables
**Solution**: Ensure TAURI_SIGNING_PRIVATE_KEY and TAURI_SIGNING_PRIVATE_KEY_PASSWORD are set correctly. Consider using Docker secrets for sensitive data.

7. Issue: Directory Not Found
**Solution** : Verify that all paths specified in the Dockerfile exist and are correct. Use debugging steps to check directory contents.


@Pranav0-0Aggarwal , @Rajgupta36  :  can you please suggest if there are any additional steps, tools, or prerequisites that I might have missed.

**Comment by Rajgupta36** [comment]
@Jibesh10101011, the frontend Docker container is not running directly, and there are some dependencies missing in the Dockerfile. I am working on fixing it before creating the documentation

**Comment by Rajgupta36** [comment]
# Backend Docker Setup for PictoPy

This guide provides step-by-step instructions for building and running the PictoPy backend using Docker.

## Table of Contents

1. [Prerequisites](#prerequisites)
2. [Building the Docker Image](#building-the-docker-image)
3. [Running the Docker Container](#running-the-docker-container)
4. [Verifying the Container](#verifying-the-container)
5. [Accessing the Application](#accessing-the-application)
6. [Stopping the Container](#stopping-the-container)
7. [Troubleshooting](#troubleshooting)

## Prerequisites

Before you begin, ensure you have the Docker installed on your machine

- Verify the installation by running:
  ```bash
  docker --version
  ```

## Building the Docker Image

1. Open a terminal and navigate to your project's root directory.

2. Go to Backend directory

   ```bash
   cd backend
   ```

3. Run the following command to build the Docker image, replacing `<image_name>` with your desired image name:

   ```bash
   docker build -t <image_name> .
   ```

4. Wait for the build process to complete. This may take a few minutes depending on your internet speed and system performance.

## Running the Docker Container

Once the image is built, you can run a container using the following command:

```bash
docker run -d -p 8000:8000 --name <container_name>  <image_name>
```

- `-d`: Runs the container in detached mode (in the background).
- `-p 8000:8000`: Maps port 8000 on the host to port 8000 in the container.
- `--name <container_name>`: Names the container for easier management.
- `<image_name>`: Specifies the image to use (the one we just built).

## Verifying the Container

To check if the container is running:

```bash
docker ps
```

You should see an entry for `<container_name>` with the status `Up`.

## Accessing the Application

Open a web browser or frontend to access the application at:

```
http://localhost:8000
```

## Stopping the Container

If you need to stop the container:

```bash
docker kill <container_id>
```

## Troubleshooting

1. **Port already in use**: If you get an error saying the port is already in use, you can either:

   - Stop the process using port 8000, or
   - Change the port mapping in the `docker run` command (e.g., `-p 8001:8000`)

2. **Container exits immediately**: Check the container logs:

   ```bash
   docker logs <container_name>
   ```

3. **Permission issues**: Ensure that `run.sh` has execute permissions(for linux only):

   ```bash
   chmod +x run.sh
   ```

   Then rebuild the Docker image.

Remember to rebuild your Docker image (`docker build -t <image_name> .`) after making any changes to your application or Dockerfile.

For more advanced Docker usage , view the [Docker documentation](https://docs.docker.com/get-started/).

**Comment by Jibesh10101011** [comment]
@Rajgupta36 

![image](https://github.com/user-attachments/assets/94da9d52-dda6-4f79-8f57-ce6115c5210a)


![image](https://github.com/user-attachments/assets/6b1d23a6-8ade-468b-ae26-45c85c36be8d)

The frontend opens in web view but does not work in desktop view due to Docker's limitations.

In the previous code if you update vite.config.ts 

![image](https://github.com/user-attachments/assets/6d8815c2-c0a6-4432-8552-5b28e4cc8e99)

to : 

server: {
    host: true,
    port: 1420,
    strictPort: true, // Ensures Vite fails if the port is unavailable
    watch: {
      // 3. tell vite to ignore watching `src-tauri`
      ignored: ['**/src-tauri/**'],
    },
    
    
The host: true option ensures the server is accessible externally (binds to 0.0.0.0).
Now you can access the frontend via a browser. However, as a desktop application, this approach does not work.

The issue arises because the Tauri application attempts to render a graphical user interface (GUI) using GTK within a Docker container. Containers generally lack access to a display environment (such as X11 or Wayland), causing GTK to fail with the warning:
"Cannot open display."

**Comment by Rajgupta36** [comment]
@Jibesh10101011 , you using git it also have x that's  provide display access. for linux we need x and for windows can we use multiple things

**Comment by Rajgupta36** [comment]
@Jibesh10101011 , please check discord . i send you a message

**Comment by ChampGupta** [comment]
Hello mentors, I would like to contribute to this issue please assign me if possible.

**Comment by Pranav0-0Aggarwal** [comment]
hey guys @Jibesh10101011 @Rajgupta36 what's the update
plz ping me with updates on discord.
