### ISSUE TITLE
BUG: Handling JSON Serialization Errors and Interrupted Server Shutdowns Gracefully

### ISSUE THREAD

**Issue by Jibesh10101011** [AOSSIE-Org/PictoPy#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/user-attachments/assets/8fd2d641-9df9-42df-bca8-8c3f90a743b6

### Problem 1 : JSON Serialization Error

When adding a folder from the frontend, the backend performs the expected operation, but the following error occurs:

`TypeError: Object of type IFDRational is not JSON serializable`

### Problem 2 : Server Shutdown Error

When stopping the backend server using Ctrl+C, the server terminates but raises a complex traceback error. The critical parts of the error include:

1. **asyncio.exceptions.CancelledError** during the shutdown process.'
2. **KeyboardInterrupt and InterruptedError** when the shutdown triggers interact with multiprocessing or asyncio tasks.

This indicates that the backend server (running with Hypercorn) does not handle graceful shutdowns properly, especially with multiple processes or event loops.

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by Jibesh10101011** [comment]
@Pranav0-0Aggarwal I am working on this issue . can you assign this to me ?

**Comment by Pranav0-0Aggarwal** [comment]
sure
