### ISSUE TITLE
to perform ner on the query and compare the ner with the caption

### ISSUE THREAD

**Issue by kamisama-coder** [AOSSIE-Org/PictoPy#84]
### Describe the feature

to perform the ner using the Bert model which is a language transformer

### Add ScreenShots

![image_2024-11-30_152529296](https://github.com/user-attachments/assets/f7e54311-4191-443f-9e90-548a27ae023f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by igennova** [comment]
Can u elaborate this issue more bro

**Comment by kamisama-coder** [comment]
want to search the image based on caption so using ner to find the names in the caption to locate the photo

**Comment by kamisama-coder** [comment]
solved #84
