### ISSUE TITLE
BUG: The dropdown menu of filter is not scrollable 

### ISSUE THREAD

**Issue by igennova** [AOSSIE-Org/PictoPy#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've found an issue in PictoPy: when there are a large number of tags for filters, we can't scroll through them. The expected behavior should be that we can scroll the dropdown menu. I've attached a video for reference.

https://github.com/user-attachments/assets/30942dd3-06d1-4b7f-8293-e99e2f791778

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by igennova** [comment]
@Pranav0-0Aggarwal 
 Please assign this issue to me

**Comment by Pranav0-0Aggarwal** [comment]
done
