### ISSUE TITLE
Feat:Add Image Deletion Functionality for Folders in Pictopy

### ISSUE THREAD

**Issue by Jibesh10101011** [AOSSIE-Org/PictoPy#96]
### Describe the feature

**Currently, Pictopy allows users to add images from a folder but lacks the functionality to delete specific images after they have been added. This feature enhancement involves implementing the ability to delete individual images from a folder after they are uploaded.**

1. Add a delete option for individual images in the UI.
2. Ensure the deletion updates the folder's image list dynamically.
3. Maintain compatibility with the existing folder structure and UI workflow.

This improvement will enhance user control over their uploaded content and improve the overall user experience.

### Updated UI :

![text not visible](https://github.com/user-attachments/assets/9ad06aa4-d8de-43e8-b110-1ddb52ad70e8)

And also want to update bg-white to bg-gray-900 (previous background color)

### Video Demonstration of the Updated Feature

https://github.com/user-attachments/assets/74cecb4b-77f7-4ceb-9654-eac37a6b92b6

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Jibesh10101011** [comment]
@Pranav0-0Aggarwal I am working on this new feature , can you assign this to me ?

**Comment by Pranav0-0Aggarwal** [comment]
Done
