### ISSUE TITLE
Feat:Frontend Unit test setup integration 

### ISSUE THREAD

**Issue by yashpandey06** [AOSSIE-Org/PictoPy#97]
## Description

Currently, the frontend codebase lacks sufficient unit tests to ensure the reliability and maintainability of the application. Unit tests are essential for catching bugs early, improving code quality, and providing confidence when making changes or adding new features.

This issue proposes the addition of unit tests for the frontend using a testing library such as [Jest](https://jestjs.io/) and [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) (if applicable for React-based projects). These tools are widely used in the industry and provide a robust framework for testing JavaScript and React components.

## Benefits

1. **Improved Code Quality:** Unit tests help identify bugs and edge cases early in the development process.
2. **Refactoring Confidence:** With unit tests in place, developers can refactor code without fear of breaking existing functionality.
3. **Documentation:** Unit tests serve as a form of documentation, showing how components and functions are expected to behave.
4. **Faster Debugging:** When a test fails, it pinpoints the exact location of the issue, making debugging faster and more efficient.

## Proposed Process

1. **Choose a Testing Framework:**
   - Use Jest for JavaScript/TypeScript testing.
   - Use React Testing Library for testing React components (if applicable).

2. **Write Tests for Core Components and Functions:**
   - Identify critical components and functions in the frontend codebase.
   - Write unit tests to cover their expected behavior.

3. **Set Up Test Coverage Reporting:**
   - Configure Jest to generate test coverage reports.
   - Aim for a minimum test coverage threshold (e.g., 80%).

4. **Integrate Tests into CI/CD Pipeline:**
   - Ensure that tests are run automatically during the CI/CD process to prevent regressions.

### Add ScreenShots

<img width="847" alt="Screenshot 2024-12-04 at 8 08 55 PM" src="https://github.com/user-attachments/assets/a161f132-e88f-448c-b47c-a802959f6bc7">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashpandey06** [comment]
@Pranav0-0Aggarwal  let me know your views so that we can discuss it further !

**Comment by ssparser** [comment]
hey @yashpandey06 I am also interested to work on this issue.

**Comment by Raakshass** [comment]
i want to work on this issue

**Comment by AasmitPadea** [comment]
I would like to work on this issue can you assign this issue to me and i would prefer to use jest and react testing library both so the system works properly

**Comment by Spoorthy1423** [comment]
Hey, can u please assign me this issue, @yashpandey06 , i would love to solve this issue

**Comment by Pranav0-0Aggarwal** [comment]
Too early for unit testing.
Closing this issue.
