### ISSUE TITLE
BUG: Add Folder in Ai tagging Button Not Visible Until Hovered

### ISSUE THREAD

**Issue by zenitsu0509** [AOSSIE-Org/PictoPy#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/user-attachments/assets/9e2bfd4d-f97a-4869-9d13-94b7e9f04a9c
**Title:**\
"The 'Add Folder' Button Becomes Visible Only on Hover"

**Description:**\
The "Add Folder" button is not visible on the interface unless hovered over, causing usability issues for users attempting to locate and interact with it.

**Steps to Reproduce:**

1.  Open the interface and navigate to AI tagging.
2.  Locate the area where the "Add Folder" button is expected.
3.  Observe that the button is not initially visible.
4.  Hover over the area, and the button becomes visible.

**Expected Behavior:**\
The "Add Folder" button should always be visible without requiring a hover action, ensuring better accessibility and usability.

**Environment:**

-   **Operating System:** Windows 11
-   **Browser/Platform:** Chrome 119
-   **Version:** Latest version (commit ID: 45ebc8e5)

**Additional Context:**

-   Attached a screen recording to demonstrate the issue.
-   This behavior may confuse new or inexperienced users, as the button's existence is not immediately apparent.

### Record

- [X] I agree to follow this project's Code of Conduct

**Comment by Rajgupta36** [comment]
Hi @zenitsu0509 , have you worked on that issue?

**Comment by Jibesh10101011** [comment]
@zenitsu0509 this issue is already described in #96

**Comment by zenitsu0509** [comment]
I am still facing this issue did you are working on this issue @Jibesh10101011

**Comment by Jibesh10101011** [comment]
Yes @zenitsu0509  I have already resolved this issue, and my PR is currently under review

**Comment by zenitsu0509** [comment]
nice👍
